[tool.black]
line-length = 120
target-version = ['py310']

[tool.isort]
profile = "black"
line_length = 120
lines_after_imports = 2

[tool.pytest.ini_options]
log_cli = true
log_cli_level = "DEBUG"
log_cli_format = "[%(levelname)5s] %(message)s"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
